
    function showanswer(questionNumber) {
        let answerContainer = document.getElementById("answer-container");

       let answers = [
    "", 
    "I was able to see that you have successfully directed your domain manager to our names server. In addition, I have checked your records and they are as well directed and defined properly. Please take in consideration that when you Implement a new website Into our services, it will usually take some time until our domain will receive your website details. It is recommended to clean the computer cache memory through Browser’s settings. Your website details should be added to our Domains shortly. If the issue repeats itself, you are welcome to contact us again and we will make a deeper check through your account.",
    "Cloudflare CDN service indeed gives perforation for the closest server located near the user. The reason that your website received an IP Address of one of our servers located in California can be related to some actions that the CDN service does automatically:\n\n- Cloudflare servers can transfer a request for a main server Located in California if there is too much traffic in one of the Servers located in Europe.\n- There are some calculations regarding a change in location of the server like - storage perforations or routing issues.\n- Cloudflare Geolocation service can give an IP address that does not point necessary on his location, due several reasons of Security, decoding and load balancing management.\n\nIn addition I will recommend to check CDN settings in your account, and to check the ‘Load balancing’ perforation. Check that you use “Argo smart routing” service. If you want to check the location of the server, use ping command with your computer’s command prompt.",
    "Worker that you recently added to your Cloudflare account can find difficulties with query the website if you didn’t marked his role properly. If his role has been set for example as a DNS Administrator, he might not have full permissions. In this case I will recommend for setting again your worker's role in your account as: Administrator or Super Administrator. If the issue persists, it could be related to your DNS settings or SSL certificate. Since your website is hosted through Namecheap, I suggest verifying that your SSL certificate is up to date and active in your Namecheap account. Ensure that the nameservers are correctly pointed to Cloudflare. I had Reviewd your Cloudflare DNS records and I can confirm that the names and IP addresses are correctly configured, let us know if you have any further questions related to workers assignment through Cloudflare account.",
    "Cloudflare Nameservers are different from Open DNS and Google DNS servers because Cloudflare services include DDOS protection along with CDN service and other protection and efficiency services. It is not possible to use Cloudflare name servers while using your host’s DNS for the same domain. Cloudflare service will demand by definition to use Cloudflare’s Name servers even if you are using a different hosting service for your website, in order to ensure all of the services of Cloudflare that mentioned above. Transferring DNS servers from services such as Open DNS or Google DNS to Cloudflare DNS and CDN servers ensures higher efficiency and protection for your website.",
    "The issue that you are describing says that Cloudflare servers don't execute caching on your website resources. You will need to go to your Caching settings in your Cloudflare account and adjust the following settings:\n\n- Search for the ‘Caching’ tab in the left menu, under that tab press ‘Configure’.\n- Check that ‘Caching level’ is marked as Standard, No Query String or Ignore Query string.\n- Check if Development Mode is marked as active, if so it can prevent Cloudflare from saving your Cache content, You will need to turn it off.\n- It might be necessary to clean Cache memory through the ‘Purge Cache’ tab, this action can update the Cache content of your website.",
    "In order to redirect a visitor with a specific agent to a different page, you will need to deploy a script into your account. You will need to search for ‘Workers’ tab in your Cloudflare settings, then you will need to create a new worker and you will have an option of ‘start from a template’, choose the redirect template and move on until you finish the process and press save and deploy. This script will allow you to make the necessary adjustment through Cloudflare without changing your code."
];


      
        answerContainer.innerHTML = answers[questionNumber];
        answerContainer.style.display = "block"; 
    }